// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi7MSN7-n0SVwALKhFJdBhvhXLrLBRXZo',
    appId: '1:738569132461:web:08fb35630e9dd074216924',
    messagingSenderId: '738569132461',
    projectId: 'gwelling-ee276',
    authDomain: 'gwelling-ee276.firebaseapp.com',
    storageBucket: 'gwelling-ee276.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRJssiekvWOZbA7i4of395PLqHRRkdcFo',
    appId: '1:738569132461:android:4980400b1563b601216924',
    messagingSenderId: '738569132461',
    projectId: 'gwelling-ee276',
    storageBucket: 'gwelling-ee276.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd3txzgB_NIfvWCkplXn58uBwGQii8_v0',
    appId: '1:738569132461:ios:1cba6c9b09350dfb216924',
    messagingSenderId: '738569132461',
    projectId: 'gwelling-ee276',
    storageBucket: 'gwelling-ee276.appspot.com',
    iosClientId: '738569132461-qfl1s1rvj72hddd2unpaheaknino6vha.apps.googleusercontent.com',
    iosBundleId: 'com.yusael.hookUpRent',
  );
}
